### ISSUE TITLE
Update to 6.2.5

### ISSUE THREAD

**Issue by pachulo** [JungleRobba/postman-snap#1]
It seems that the latest version now is 6.2.5

**Comment by junglerobba** [comment]
I am no longer maintaining this snap, please check out https://github.com/snapcrafters/postman
At the moment all it would take to update is rebuilding the snap and reuploading it.

**Comment by pachulo** [comment]
OK, so they also need to modify the contact in the snap, because it's still pointing here.
Thanks!
